### ISSUE TITLE
Session: Teaching for the world we want to live in

### ISSUE THREAD

**Issue by samclifford** [ACEMS/ECRretreat2017Nov#1]
The statistics/mathematics education we all received in the 1990s-2000s was likely from lecturers who'd studied and received their PhDs in the 1980s-1990s, a time before things like the internet, YouTube, R and other modern conveniences were invented and widely available to university students. The university world has changed even since we were undergrads.

* Do we have to deliver the same classes that we learned from?
* Are there things that are here now or on the horizon that are worth teaching the undergrads of the 2010s?
* Do we risk throwing the baby out with the bathwater?

In this session I'd like to run a discussion about what we teach, how and why. I'll be bringing my experiences as a lecturer for a first year maths/stats class delivered to undergrad science students, how we assess preparedness, the redesign of learning activities and material, and assessment structure.

Assumed knowledge: It'd be helpful if you've at least tutored undergraduate classes.
Things to bring: Nothing required, but if you want to bring along an example of something you feel is a bit innovative or would like feedback on, that'd be great.

**Comment by samclifford** [comment]
If need be I can roll this into the discussion about challenged faced by ECRs.

**Comment by jesse-jesse** [comment]
I'm not technically a participant of the ECR retreat, But I this topic is pretty interesting to me.

**Comment by samclifford** [comment]
Thanks for the chat the other day on this. I think we came away with the ideas of using live coding to demonstrate in lectures rather than just presenting the completed analysis, ensuring that we put some thought into how we structure the learning activities across the semester, creating additional videos beyond the lecture recordings and using domain-relevant problems for service teaching.

An issue we highlighted was that being given either no freedom (deliver the same material we've always presented) or too much freedom (teach whatever) doesn't necessarily lead to good outcomes. Teaching in a smaller setting allows you to adjust on the fly when you've pitched it at the wrong level, and having a "now you try" approach is more feasible in workshops, where students work in groups to solve a problem under the supervision of a tutor, than in lectures where you can sit there passively for two hours.
