### ISSUE TITLE
Session: Making my research reproducible

### ISSUE THREAD

**Issue by jesse-jesse** [ACEMS/ECRretreat2017Nov#3]

**Comment by Arthur-Hung** [comment]
Hi Jessie,

We can use knitr to make research reproducible. I have been using this tool recently. Please have a look at the link below:

https://yihui.name/knitr/

Regards,
Arthur

**Comment by jesse-jesse** [comment]
Hey @Arthur-Hung , I love knitr.. i use Rmarkdown a fair bit. Would be interested in hearing how others manage their reproducible research workflow.
