### ISSUE TITLE
Favourite Beach Games?

### ISSUE THREAD

**Issue by jesse-jesse** [ACEMS/ECRretreat2017Nov#6]
On Monday afternoon we will have a BBQ on the beach with the attendees of the student retreat. We need some beach game ideas??

**Comment by paul1010** [comment]
There's the quintessential: beach cricket, beach volleyball, burying someone alive? I think there are a few keen badmington players too (isn't Benoit badmington champ?)

**Comment by zzzchong** [comment]
We can also do something like tug of war, beach soccer, darts.

**Comment by zzzchong** [comment]
Maybe **riddles** is not a bad idea.

**Comment by samclifford** [comment]
@zzzchong "What have I got in my pocket?"

**Comment by tarunendumapder** [comment]
What about some "badminton" or "beach volley"? We have some badminton player here in ACEMS QUT.

**Comment by jesse-jesse** [comment]
I have croquet, and am continuing to collect games.

**Comment by matiasq** [comment]
What about some surfing? Given that we are in Surfers paradise after all :)

**Comment by jesse-jesse** [comment]
I don't have a surf board, but keen for swimming in the waves. Maybe there are some places for surf lessons?

**Comment by jesse-jesse** [comment]
oops.. pressed the wrong button.. did mean to close the issue
